name: Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Pull images
      run: make pull

    - name: Build
      run: make build

    - name: Upload validation artifact
      uses: klakegg/github-upload@v0.9.1
      if: startsWith(github.ref, 'refs/tags/')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        file: "target/org.unece.uncefact.cii-${TAG}.asice"
        label: "Validation artifacts for VEFA Validator 2.x"
        type: "application/vnd.difi.validator.v2+zip"
